### ISSUE TITLE
Compiling under windows

### ISSUE THREAD

**Issue by PeggerWed** [achilikin/bdfe#1]
Is it possible to have it compiled under windows?

Error:
rm -f bdfe
rm -f _.o
g++ -c -Wall -Werror -g -DOSSD_TARGET=OSSD_IF_LINUX main.c -o main.o
main.c: In function 'int main(int, char__)':
main.c:89:25: error: 'basename' was not declared in this scope
   usage(basename(argv[0]));
                         ^
main.c:95:26: error: 'basename' was not declared in this scope
    usage(basename(argv[0]));
                          ^
main.c:211:22: error: 'basename' was not declared in this scope
  file = basename(file);
                      ^
make: *_\* [main.o] Error 1

**Comment by achilikin** [comment]
Probably basename() is not part of Cygwin. Check if it is available in the latest Cygwin version.

**Comment by achilikin** [comment]
I've added local replacement for basename, now local function "filename" is called instead.
